branch-defaults:
  master:
    environment: communityfund-production
    group_suffix: null
deploy:
  artifact: payload.zip
global:
  application_name: communityfund
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-deploy
  repository: null
  sc: git
  workspace_type: Application
