/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

/*
  Grants
*/
export const GRANT_INPUT_CHANGED = 'GRANT_INPUT_CHANGED';
export const GRANT_FORM_VALIDATION_ERRORS = 'GRANT_FORM_VALIDATION_ERRORS';
export const GRANT_FORM_SUBMIT_SUCCESS = 'GRANT_FORM_SUBMIT_SUCCESS';

/* Submissions */
export const GET_SUBMISSION_SUCCESS = 'GET_SUBMISSION_SUCCESS';

/* Voting */
export const VOTE_ADD_COMMENT = 'VOTE_ADD_COMMENT';
export const VOTE_CAST_VOTE = 'VOTE_CAST_VOTE';
export const VOTE_CAST_VOTE_SUCCESS = 'VOTE_CAST_VOTE_SUCCESS';
export const VOTE_CAST_VOTE_ERROR = 'VOTE_CAST_VOTE_ERROR';
