/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const SET_ROUTE_OVERRIDE = 'SET_ROUTE_OVERRIDE';

/*
  Grants
*/
export const GRANT_INPUT_CHANGED = 'GRANT_INPUT_CHANGED';
export const GRANT_FORM_VALIDATION_ERRORS = 'GRANT_FORM_VALIDATION_ERRORS';
export const GRANT_FORM_SUBMIT_SUCCESS = 'GRANT_FORM_SUBMIT_SUCCESS';

/* Submissions */
export const GET_SUBMISSION_SUCCESS = 'GET_SUBMISSION_SUCCESS';

export const GET_SUBMISSION_STATUS_SUCCESS = 'GET_SUBMISSION_STATUS_SUCCESS';

/* Voting */
export const VOTE_ADD_COMMENT = 'VOTE_ADD_COMMENT';
export const VOTE_CAST_VOTE_SUCCESS = 'VOTE_CAST_VOTE_SUCCESS';
export const VOTE_CAST_VOTE_ERROR = 'VOTE_CAST_VOTE_ERROR';

/* Topics */
export const TOPICS_UPDATE_DATA = 'TOPICS_UPDATE_DATA';

export const USERS_UPDATE_DATA = 'USERS_UPDATE_DATA';
